apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:A4YXQGU3pCmCQC1EPrwdtuge2oBr,iv:LYzgOMqi5ob8XYAGuFjxCCq0uDbg762489ojoKDvkpU=,tag:A/MZ/60luql0BoRSBIfouQ==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:5KGokmJZq66dXl7ANcISg0LXxcx06b9kuYilF/3cNo0DuKIDSw==,iv:OD3t2VqANLcReLBzeB3XtA8rHwiRFOebhqOUNU+2W2E=,tag:VS4YR8Nsc7EFPlN3KWa85w==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:R+mj9IczzpJemvNnsFl4Htrx,iv:8kv89r2bzJjCLyeyCTQrXmXddWTEzOB/VhJnIOMdd4I=,tag:L9YeaqUgr2vsHanrZ10lxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s9tty2sjqqzkgc3dj44rcrvs99vpnfv7zjezgvgsjf6ncc4jpp9sm0pwvn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSzU3MEN1bDFUZTJGaGxG
            VVp3UVNLZ0FxendmcmtCZytqcmZLN0tlQzE0CnZha1dhYkRNcWdBeUdBZE1Pb0VC
            S1lIaHF0SEJvNnZ3UHJqa1c1M0x0aTQKLS0tIDFENjRtNFlZMWxaN3RoLzVQY3BB
            dUJkTXVYYmFhV3hSdHgycHJkeEtVRkkKiHg6LTxgfaT8H9RmdKkJjqBuaPSLR6ka
            pyJYLHK/2JvJShLdh+6IMiPxDKtmuyiuREEiFElPx7x0mxePIPlNMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-23T15:57:00Z"
    mac: ENC[AES256_GCM,data:W60z6dYst5pRskVeau37XQCOpYe31gBa+nGyFhyl9wwws992rU6VAyJnzTyZD9AvMbXWiMT6p1XM+9bovN3vcDGCrXwt1MMmsrymMWWP/LGjKfWmPqXQoRmE7S3OiotCy3eG1jgTeaISKA6Hprs8uNLnWQVXMUTShAg9cWF6ses=,iv:oZS70HWitVonJs0gQC9KzFtAbzsgSexWyJ7/oXrR3pY=,tag:DukrWc4Hjishz38BG3E00A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
